version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "311846519160"
    AWS_DEFAULT_REGION: "us-east-1"
    REPOSITORY_URI: "311846519160.dkr.ecr.us-east-1.amazonaws.com/firstprojectecr"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      

  build:
    commands:
      
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      

  post_build:
    commands:
      
      - docker push $REPOSITORY_URI:latest
      
      
      - echo '[{"name":"react-frontend-container","imageUri":"'$REPOSITORY_URI:$IMAGE_TAG'"}]' > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
